name: .NET Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-2019

    env:
      Solution_Name: M3Ueditor.sln      
      Test_Project_Path: M3Ueditor.UnitTests\M3Ueditor.UnitTests.csproj
      Wap_Project_Directory: M3Ueditor
      
    steps:

    - uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Restore Packages
      run: nuget restore $env:Solution_Name 

    - name: Restore the application
      run: msbuild $env:Solution_Name -t:rebuild /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
          name: M3Ueditor-artifact
          path: ${{ github.workspace }}/M3Ueditor/bin/Release/*
          retention-days: 5
      
    - name: echo github.workspace
      run: echo "${{ github.workspace }}"  

    - name: pwd
      run: pwd    

    - name: dir
      run: dir    
      
    - name: dir github.workspace
      run: dir "${{ github.workspace }}"  
      
    - name: print M3Ueditor
      run: dir "${{ github.workspace }}/M3Ueditor/"

    - name: Create zip
      uses: vimtor/action-zip@v1
      with:
        files: ${{ github.workspace }}/M3Ueditor/bin/Release/ ChangeLog.txt LICENSE
        dest: Release.zip


    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: Release
        name: M3Ueditor v.12
        body_path: ./M3Ueditor/ChangeLog.txt
        files: |
          Release.zip
          
    - name: dir
      run: dir

    - name: version
      run: echo "::set-output name=version::$(./M3Ueditor/bin/Release/M3Ueditor.exe --version)"
      id: version

    - name: echo github.workspace
      run: echo "${{ steps.version.outputs.version }}"  
